### PR TITLE
'sortFiles' method - relative path fix

### PR DESCRIPTION
**Pull request by hopkins700**
This fix should solve the following issue: https://github.com/aurelia/tools/issues/35

### CODE REVIEW

**Comment by hopkins700** [comment]
Thanks, Rob. I just used aurelia environment as an example to build my own modules..  Anyway I made a pull request. Please, merge it with the main branch if you'll find it useful

**Comment by EisenbergEffect** [comment]
Thanks! I appreciate you taking the time to work on it!

I noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

**Comment by hopkins700** [comment]
Thanks Rob! I just signed the CLA

**Comment by doktordirk** [comment]
not having checked tht code, but i do know i might use that feature

**Comment by EisenbergEffect** [comment]
Got it merged. Thanks!

**Pull request merged**
