### PR TITLE
chore(babel-eslint): bumped peer dependencies

### PR DESCRIPTION
**Pull request by DrzwiPercepcji**

### CODE REVIEW

**Comment by DrzwiPercepcji** [comment]
@EisenbergEffect Could you have a look at it if you have a moment? Similar to https://github.com/aurelia/tools/commit/442a6bfd1881be7845af9c9f95f15c46b2fa1417.

**Comment by bigopon** [comment]
Thanks @DrzwiPercepcji , this repo is no longer taking new changes. We will be archiving it.

**Comment by DrzwiPercepcji** [comment]
@bigopon is there any other new repo where I can create PR for these changes?

**Comment by bigopon** [comment]
What kind of changes do you want to create?

**Comment by DrzwiPercepcji** [comment]
@bigopon bump these peer dependencies for aurelia-tools@2.0.0.

**Comment by bigopon** [comment]
What package that uses aurelia tool that you use? You can just upgrade it to latest, all our packages no longer use aurelia tool I believe.
Also, you can force resolution of dependencies with resolutions or overrides with npm.

**Comment by szymon-nowak-rel** [comment]
Writing from corporate account here, I will check if I can remove aurelia-tools from project. If so, I will close the PR.

**Comment by DrzwiPercepcji** [comment]
@bigopon looks like we could remove Aurelia Tools from our project, thanks. I am closing this.

**Pull request closed without merging**
